name: Defect report
description: Create a report to help us improve
title: "[Defect]: <TITLE_OF_DEFECT>"
body:
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: >-
        A summary of the environment in which the defect was found, including but not limited to the following.


      placeholder: >-
        Include any information regarding the device, operating system, web browser, links, etc.


      value: |-
        - **Device**:
        - **OS Version**:
        - **Browser Version**:
        - **Link**:
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: >-
        A list of steps that, when followed, will precisely reproduce the defect.


      placeholder: >-
        A list of steps that, when followed, will precisely reproduce the defect.


      value: |-
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: behavior-expected
    attributes:
      label: Expected Behavior
      description: A clear and concise summary of what you expected to happen.
      placeholder: I expected ...
    validations:
      required: true
  - type: textarea
    id: behavior-actual
    attributes:
      label: Actual Behavior
      description: >-
        A clear and concise summary of what actually happened, i.e. the defective behavior.


      placeholder: What actually happened was ...
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: >-
        Any additional notes, screenshots, etc. for the team to consider to help resolve this defect.


      placeholder: >-
        TIP: You can attach images or log files by clicking this area to highlight it and then dragging files inside.

