name: Epic
description: "Create an epic "
title: "[Epic]: <TITLE_OF_EPIC>"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        A description of a large body of work that can be broken down into a number of smaller stories/tasks.

    validations:
      required: true
  - type: textarea
    id: stories
    attributes:
      label: User Stories / Tasks
      description: Lists of stories/tasks that make up the items to fulfill the epic.
      value: |-
        - [ ] 
        - [ ] 
        - [ ]
  - type: textarea
    id: notes
    attributes:
      label: Notes
