name: Task
description: Create a task
title: "[Task]: <TITLE_OF_TASK>"
body:
  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: An overview of the task.
    validations:
      required: true
  - type: textarea
    id: action-items
    attributes:
      label: Action Items
      description: A list of action items to complete the task.
      placeholder: A list of action items to complete the task.
      value: |-
        - [ ]
        - [ ]
        - [ ]
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: >-
        Any additional notes, resources, instructions, etc. to help complete this task.


      placeholder: >-
        TIP: You can attach images or log files by clicking this area to highlight it and then dragging files inside.

