name: Task
title: "<title>"
description: A task with action items to complete.
projects:
  - "hackforla/21"
body:
  - id: description
    type: textarea
    attributes:
      label: Description
      description: >-
        A brief description of the task.
    validations:
      required: true

  - id: action-items
    type: textarea
    attributes:
      label: Action Items
      description: >-
        A list of action items to complete the task.
      value: |-
        - [ ]
    validations:
      required: true

  - id: additional-information
    type: textarea
    attributes:
      label: Additional Information
      description: >-
        Include any other information that might be relevant to the epic, such as dependencies, constraints, or related projects.
      placeholder: >-
        e.g., This epic is dependent on the completion of [related project], or This epic must comply with [specific regulations].
