name: Onboarding
description: Template for onboarding new members.
title: "[Onboarding] <Name>"
body:
  - type: input
    id: name
    attributes:
      label: First/Preferred Name
      description: Enter your first or preferred name.
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Email Address
      description: Enter your email address.
    validations:
      required: true
  - type: input
    id: github-username
    attributes:
      label: GitHub Username
      description: Enter your GitHub username.
    validations:
      required: true
  - type: input
    id: slack-name
    attributes:
      label: Slack Display Name
      description: Enter your name as it appears on Slack.
    validations:
      required: true
  - type: dropdown
    id: team
    attributes:
      label: Team
      description: Which team will you be joining?
      options:
        - Data
        - Development
        - Product
        - UX
    validations:
      required: true
  - type: markdown
    attributes:
      value: |-
        ---

        The following sections are to be completed with a Product Manager.
  - type: dropdown
    id: lead
    attributes:
      label: Lead
      description: Are you joining as a lead for the team selected above?
      options:
        - "No"
        - "Yes"
  - type: checkboxes
    id: onboarding-github
    attributes:
      label: "Onboarding: GitHub"
      options:
        - label: "[All] Set GitHub profile to public"
          required: false
        - label: "[All] Set up 2FA for GitHub account"
          required: false
        - label: '[All] Add to the lucky-parking-write team as "maintainer"'
          required: false
  - type: checkboxes
    id: onboarding-roster
    attributes:
      label: "Onboarding: Roster"
      options:
        - label: "[All] Add new team member to roster"
          required: false
        - label: "[All] Note if GitHub profile requirement is public"
          required: false
        - label: "[All] Note if 2FA GitHub account is set up"
          required: false
  - type: checkboxes
    id: onboarding-google
    attributes:
      label: "Onboarding: Google"
      options:
        - label: "[All] Invite to Google Calendar events"
          required: false
        - label: "[Leads] Add to team email"
          required: false
        - label: >-
            [Data, Dev, UX] Grant access to the shared Google Drive as a
            "content manager"
          required: false
        - label: '[PM] Grant access to the shared Google Drive as a "manager"'
          required: false
  - type: checkboxes
    id: onboarding-slack
    attributes:
      label: "Onboarding: Slack"
      options:
        - label: "[All] Add to the general #lucky-parking channel"
          required: false
        - label: "[Leads] Add to the lead team #lucky-parking-core channel"
          required: false
        - label: >-
            [Data] Add to the development team #lucky-parking-data-science
            channel
          required: false
        - label: "[Devs] Add to the development team #lucky-parking-dev channel"
          required: false
  - type: checkboxes
    id: onboarding-figma
    attributes:
      label: "Onboarding: Figma"
      options:
        - label: '[All] Invite to Figma design file as "can view"'
          required: false
  - type: checkboxes
    id: onboarding-1password
    attributes:
      label: "Onboarding: 1Password"
      options:
        - label: "[All] Invite to Hack for LA account"
          required: false
        - label: "[All] Add to Lucky Parking vault"
          required: false
        - label: "[All] Add to the Lucky Parking Project Design vault"
          required: false
        - label: "[All] Add to the Zoom vault"
          required: false
  - type: checkboxes
    id: onboarding-training
    attributes:
      label: "Onboarding: Training"
      options:
        - label: "[Leads] Logging into team account"
          required: false
        - label: "[All] Inviting to calendar events"
          required: false
        - label: >-
            [All] Using the Zoom spreadsheet, 1Password vaults, and Zoom
            accounts
          required: false
  - type: textarea
    id: notes
    attributes:
      label: Notes
  - type: markdown
    attributes:
      value: >-
        ---


        ## References


        **Figma**


        - [Figma Design
        File](https://www.figma.com/file/R3N7mvDtlFbFgQm4OXcMih/Lucky-Parking)


        **GitHub**

        - [Configuring two-factor
        authentication](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication)

        - Teams:
          - [lucky-parking-write team](https://github.com/orgs/hackforla/teams/lucky-parking-write)

        **Roster**


        - [Roster
        spreadsheet](https://docs.google.com/spreadsheets/d/1rtou2FkVwKV7-2RKiRDXb2uAq_w0jHakFydzUhoW2dU/edit)


        **Slack**


        - [#lucky-parking](https://hackforla.slack.com/archives/CPFDMSV6V)

        -
        [#lucky-parking-core](https://hackforla.slack.com/archives/C0522K72NAU)

        - [#lucky-parking-dev](https://hackforla.slack.com/archives/C049S985R7W)

        -
        [#lucky-parking-data-science](https://hackforla.slack.com/archives/C044H1DETLH)


        **Hack for LA**

        - [Organization Onboarding/Offboarding
        Template](https://github.com/hackforla/.github-hackforla-base-repo-template/blob/main/.github/ISSUE_TEMPLATE/onboard---offboard--product.md)
