#!/usr/bin/env bash
# Create postgis_db/.env with a random POSTGRES_PASSWORD if it does not exist.
#
# Compose now requires POSTGRES_PASSWORD rather than falling back to a
# well-known default, so local setup stays one command by generating one.
# Existing .env files are never modified.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${ROOT}/.env"

if [[ -f "${ENV_FILE}" ]]; then
  if grep -qE '^POSTGRES_PASSWORD=.+' "${ENV_FILE}"; then
    echo "OK: ${ENV_FILE} already sets POSTGRES_PASSWORD"
    exit 0
  fi
  echo "ERROR: ${ENV_FILE} exists but POSTGRES_PASSWORD is empty or missing." >&2
  echo "       Add a value (see scripts/gen_secrets.sh) and re-run." >&2
  exit 1
fi

PASSWORD="$(openssl rand -base64 32 | tr -d '\n=+/' | cut -c 1-32)"

cat >"${ENV_FILE}" <<EOF
# Generated by scripts/ensure_env.sh for local development. Not for production
# credentials — see .env.example and deploy/VPS.md.
POSTGRES_DB=lucky_parking
POSTGRES_USER=lucky
POSTGRES_PASSWORD=${PASSWORD}

API_PORT=8000
WEB_PORT=8080

# Localhost only: no API key or basic auth prompt.
ALLOW_UNAUTHENTICATED=1
RATE_LIMIT_PER_MINUTE=0
API_DOCS_PUBLIC=1

# Load citations from raw_data/ on first boot.
SKIP_CITATIONS_LOAD=0
EOF

chmod 600 "${ENV_FILE}"
echo "Wrote ${ENV_FILE} with a generated POSTGRES_PASSWORD."
