# Create postgis_db\.env with a random POSTGRES_PASSWORD if it does not exist.
#
# Compose now requires POSTGRES_PASSWORD rather than falling back to a
# well-known default, so local setup stays one command by generating one.
# Existing .env files are never modified.
#
# Kept ASCII-only and free of .NET Core-only APIs so it runs under the Windows
# PowerShell 5.1 that ships with Windows, not just PowerShell 7+.
$ErrorActionPreference = 'Stop'

$Root = Split-Path -Parent $PSScriptRoot
$EnvFile = Join-Path $Root '.env'

function Write-Err([string]$Message) {
  [Console]::Error.WriteLine($Message)
}

if (Test-Path -LiteralPath $EnvFile) {
  $hasPassword = Select-String -LiteralPath $EnvFile -Pattern '^POSTGRES_PASSWORD=.+' -Quiet
  if ($hasPassword) {
    Write-Host "OK: $EnvFile already sets POSTGRES_PASSWORD"
    exit 0
  }
  Write-Err "ERROR: $EnvFile exists but POSTGRES_PASSWORD is empty or missing."
  Write-Err '       Add a value (see scripts\gen_secrets.ps1) and re-run.'
  exit 1
}

# See gen_secrets.ps1 for why this API and not RandomNumberGenerator::Fill.
$rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
try {
  $bytes = New-Object byte[] 96
  $rng.GetBytes($bytes)
  $password = ([Convert]::ToBase64String($bytes) -replace '[^A-Za-z0-9]', '').Substring(0, 32)
}
finally {
  $rng.Dispose()
}

$content = @"
# Generated by scripts\ensure_env.ps1 for local development. Not for production
# credentials - see .env.example and deploy/VPS.md.
POSTGRES_DB=lucky_parking
POSTGRES_USER=lucky
POSTGRES_PASSWORD=$password

API_PORT=8000
WEB_PORT=8080

# Localhost only: no API key or basic auth prompt.
ALLOW_UNAUTHENTICATED=1
RATE_LIMIT_PER_MINUTE=0
API_DOCS_PUBLIC=1

# Load citations from raw_data/ on first boot.
SKIP_CITATIONS_LOAD=0
"@

# Docker Compose does not strip a UTF-8 BOM from .env, and Windows PowerShell
# 5.1's `Set-Content -Encoding utf8` writes one. Write bytes without a BOM so
# the first variable is not read as "\ufeffPOSTGRES_DB".
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($EnvFile, ($content -replace "`r`n", "`n"), $utf8NoBom)

Write-Host "Wrote $EnvFile with a generated POSTGRES_PASSWORD."
