openapi: 3.0.3

info:
  title: Lucky Parking
  description: The Lucky Parking API
  license:
    name: UNLICENSED
  version: 1.0.0

servers:
  - url: https://luckyparking.org/api/v1

tags:
  - name: citation
    description: Parking citations
    externalDocs:
      description: Data source
      url: https://data.lacity.org/Transportation/Parking-Citations/wjz9-h9np

components:
  schemas:
    Citation:
      description: Parking citation
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        coordinates:
          $ref: "#/components/schemas/GeoPosition"
        violation_code:
          type: string
        fine_amount:
          type: string
          format: currency
    CitationFeature:
      description: Citation feature
      allOf:
        - $ref: "#/components/schemas/GeoFeature"
        - type: object
          required:
            - properties
          properties:
            properties:
              $ref: "#/components/schemas/Citation"
    CitationFeatureCollection:
      description: A collection of citation features
      allOf:
        - $ref: "#/components/schemas/GeoFeatureCollection"
        - type: object
          required:
            - features
          properties:
            features:
              type: array
              items:
                $ref: "#/components/schemas/CitationFeature"
    Date:
      description: Timestamp
      type: string
      format: date-time
    DateRange:
      description: A range of dates formatted as [from, to].
      type: array
      minItems: 2
      maxItems: 2
      items:
        $ref: "#/components/schemas/Date"
    GeoFeature:
      description: GeoJSON Feature object
      externalDocs:
        url: "https://tools.ietf.org/html/rfc7946#section-3.2"
      allOf:
        - $ref: "#/components/schemas/GeoJson"
        - type: object
          required:
            - geometry
            - properties
          properties:
            geometry:
              allOf:
                - nullable: true
                - $ref: "#/components/schemas/GeoGeometry"
            properties:
              type: object
              nullable: true
            id:
              oneOf:
                - type: number
                - type: string
    GeoFeatureCollection:
      description: GeoJSON FeatureCollection object
      externalDocs:
        url: "https://tools.ietf.org/html/rfc7946#section-3.3"
      allOf:
        - $ref: "#/components/schemas/GeoJson"
        - type: object
          required:
            - features
          properties:
            features:
              type: array
              items:
                $ref: "#/components/schemas/GeoFeature"
    GeoGeometry:
      description: GeoJSON Geometry object
      externalDocs:
        url: "https://datatracker.ietf.org/doc/html/rfc7946#section-3.1"
      allOf:
        - $ref: "#/components/schemas/GeoJson"
        - type: object
          properties:
            type:
              type: string
              enum:
                - Point
                - MultiPoint
                - LineString
                - MultiLineString
                - Polygon
                - MultiPolygon
                - GeometryCollection
          required:
            - type
          discriminator:
            propertyName: type
    GeoGeometryElement:
      description: GeoJSON Geometry object with type that is not GeometryCollection
      externalDocs:
        url: "https://datatracker.ietf.org/doc/html/rfc7946#section-3.1"
      allOf:
        - $ref: "#/components/schemas/GeoGeometry"
        - type: object
          required:
            - type
          properties:
            type:
              type: string
              enum:
                - Point
                - MultiPoint
                - LineString
                - MultiLineString
                - Polygon
                - MultiPolygon
          discriminator:
            propertyName: type
    GeoJson:
      description: GeoJSON object
      externalDocs:
        url: "https://tools.ietf.org/html/rfc7946#section-3"
      type: object
      required:
        - type
      properties:
        type:
          type: string
          enum:
            - Feature
            - FeatureCollection
            - Point
            - MultiPoint
            - LineString
            - MultiLineString
            - Polygon
            - MultiPolygon
            - GeometryCollection
        bbox:
          type: array
          items:
            type: number
      discriminator:
        propertyName: type
    GeoLinearRing:
      description: GeoJSON linear ring object
      externalDocs:
        url: "https://tools.ietf.org/html/rfc7946#section-3.1.6"
      type: array
      items:
        $ref: "#/components/schemas/GeoPosition"
      minItems: 4
    GeoPolygon:
      description: GeoJSON polygon object
      externalDocs:
        url: "https://tools.ietf.org/html/rfc7946#section-3.1.6"
      allOf:
        - $ref: "#/components/schemas/GeoGeometryElement"
        - type: object
          required:
            - coordinates
          properties:
            coordinates:
              type: array
              items:
                $ref: "#/components/schemas/GeoLinearRing"
    GeoPosition:
      description: GeoJSON position object
      externalDocs:
        url: "https://tools.ietf.org/html/rfc7946#section-3.1.1"
      type: array
      minItems: 2
      maxItems: 3
      items:
        type: number

  requestBodies:
    CitationFilters:
      description: Citation object with properties to filter through all citations
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              dates:
                $ref: "#/components/schemas/DateRange"
              geometry:
                $ref: "#/components/schemas/GeoPolygon"

  responses:
    CitationFeatureCollection:
      description: A collection of citation features
      content:
        application/json:
          schema:
            type: object
            required:
              - data
            properties:
              data:
                $ref: "#/components/schemas/CitationFeatureCollection"
    Error:
      description: Error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
              message:
                description: A human-readable message describing the error
                type: string
              path:
                type: string
                format: uri
              status:
                type: integer
              timestamp:
                type: string
                format: date-time

paths:
  /citations:
    post:
      tags:
        - citation
      summary: Find parking citations
      description: Find parking citations by dates and polygon coordinates
      requestBody:
        $ref: "#/components/requestBodies/CitationFilters"
      responses:
        200:
          $ref: "#/components/responses/CitationFeatureCollection"
        400:
          $ref: "#/components/responses/Error"
        500:
          $ref: "#/components/responses/Error"
# References:
#
# RFC7946 - The GeoJSON format
# https://tools.ietf.org/html/rfc7946
#
# OpenAPI (OAS3/Swagger) definition for GeoJSON objects
# https://gist.github.com/zit0un/3ac0575eb0f3aabdc645c3faad47ab4a
