name: Compliance

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - unassigned

jobs:
  check-for-linked-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: check-for-keywords
      id: check-for-keywords
      uses: actions/github-script@v7
      with:
        script: |
          // Retrieve body of current PR, search for 'Resolves'
          const prBody = context.payload.pull_request.body;
          const prNumber = context.payload.pull_request.number;
          const prOwner = context.payload.pull_request.user.login;
          const regex = /(?<!Example:\s*)(close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved)\s+#(\d+)/i;
          const match = prBody.match(regex);
          if (match) {
            console.log(match);
            linkNumber = match[2];
            console.log('Found issue #' + linkNumber +' linked. Checking if legit...');
            const response = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: linkNumber,
            });
            if (response.status === 200) {
              console.log('Found issue #' + linkNumber + ' in repo. PR has a properly linked issue.');
            } else {
              console.log('Couldn\'t find issue #' + linkNumber + ' in repo. Posting comment...');
            }
          } else {
            console.log('PR does not have a properly linked issue. Posting comment...');
          }
          const prComment = `@${prOwner}, this Pull Request is not linked to a valid issue. Please provide a valid issue number in the Description above, in "Linked Issues", after "Resolves # `;
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: prComment,
          });
          
