name: Integration

on:
  pull_request:
    branches:
      - main
      - stable
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
      - stable

env:
  NEXT_TELEMETRY_DISABLED: ${{ vars.NEXT_TELEMETRY_DISABLED }}
  TURBO_TELEMETRY_DISABLED: ${{ vars.TURBO_TELEMETRY_DISABLED }}

jobs:
  code-verification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - run: pnpm install --frozen-lockfile
      - run: pnpm verify
