name: Release Workflow

on:
  push:
    branches:
      - stable

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # more to come
